name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose --release
    - name: Run tests
      run: cargo test --verbose
    - name: Move artifacts
      run: mkdir staging && cp target/release/cli_todo staging
    - uses: actions/upload-artifact@v4
      with:
        name: Package
        path: staging
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose --release
    - name: Run tests
      run: cargo test --verbose
    - name: Move artifacts
      run: mkdir staging && Copy-Item target\release\cli_todo.exe staging
    - uses: actions/upload-artifact@v4
      with:
        name: Package
        path: staging
